### ISSUE TITLE
Module names are confusing

### ISSUE THREAD

**Issue by ndmitchell** [vincenthz/hs-foundation#1]
Having Overture is weird. I'd either make it Core.Prelude or Foundation. I'd probably make all the other modules Foundation.Number etc.

**Comment by vincenthz** [comment]
what about just Overture -> Core ? Foundation is a bit long to type, and also keeping the distinction could be useful in the future. for example having a clear distinction between Core part of foundation, and WIP/Unstable/Extra parts.

**Comment by ndmitchell** [comment]
Sure, Overture is a horrible name, Core is quite reasonable and has a strong relationship with the rest of the package. That said, I've never found module name length to be a real problem when writing modules, what is a problem is ambiguity - both two packages providing the same module and it not being clear which package a module comes from. I still think Foundation.* would be a good name for everything to start with, but your call. Alternatively, perhaps rename the package as Core, but that overloads against GHC-Core.

**Comment by vincenthz** [comment]
so Overture is now Core in 7626da031c00ada351a760589ea736d2b12bb81c
