### ISSUE TITLE
Add partial functions

### ISSUE THREAD

**Issue by ndmitchell** [vincenthz/hs-foundation#11]
fromJust/head/tail/fromLeft/fromRight are all useful functions. They should exist somewhere.

**Comment by vincenthz** [comment]
I agree they are useful in certain cases, but it would be nice to be able to quickly find partial functions one way or another when doing a project: at the moment grepping for a random set of function is not ideal. I haven't too much about it, but what about those options:

* put them in a specific module `Core.Partial` , just like `System.IO.Unsafe`
* make them run through a specific function: e.g. `partial head`

**Comment by ndmitchell** [comment]
The second one seems a very neat solution to the problem - you annotate uses with partiality, rather than "names" which (without tracking down the imports) aren't obvious. Very clever idea and not one I've seen before! :+1:

**Comment by vincenthz** [comment]
fixed by b87cc0be35e8ad457b729f74236d5edd4777d5dc
