### ISSUE TITLE
Add Strict pair

### ISSUE THREAD

**Issue by ndmitchell** [vincenthz/hs-foundation#15]
Often useful! Just `data Pair a b = Pair !a !b`

**Comment by vincenthz** [comment]
I've added Tuple2 .. to Tuple6 to do that. it strikes me that it would be convenient to have
`fst` `snd` .. to work on different version of tuples `(a,b)` and `Tuple a b` ?

**Comment by ndmitchell** [comment]
Do we really need up to 6? My usual mantra is lots of pairs, some triples, occasionally 4, then stop. Overloading fst seems ugly, but convenient - not sure which way I would go.

**Comment by vincenthz** [comment]
yeah you're right. At 6 you probably need a record to make sense; using a tuple of 6 is error prone I think. I'm happy to put back to 4, but generally not a problem to go less or more anyway.

For overloading `fst` and friends, I'm not sure either. Maybe the best at this stage would be to look at the overloaded solution and if that make any sense.

**Comment by vincenthz** [comment]
I came up with this:

```haskell

class Fstable a where
    type FstTy a
    fst :: a -> FstTy a

instance Fstable (a,b) where
    type FstTy (a,b) = a
    fst (a,_) = a
instance Fstable (a,b,c) where
    type FstTy (a,b,c) = a
    fst (a,_,_) = a
instance Fstable (a,b,c,d) where
    type FstTy (a,b,c,d) = a
    fst (a,_,_,_) = a
instance Fstable (Tuple2 a b) where
    type FstTy (Tuple2 a b) = a
    fst (Tuple2 a _) = a
instance Fstable (Tuple3 a b c) where
    type FstTy (Tuple3 a b c) = a
    fst (Tuple3 a _ _) = a
instance Fstable (Tuple4 a b c d) where
    type FstTy (Tuple4 a b c d) = a
    fst (Tuple4 a _ _ _) = a
```

**Comment by vincenthz** [comment]
it's definitely convenient; not sure if that's a good thing overall

**Comment by ndmitchell** [comment]
Seems the only thing that makes sense if you do overload. Not sure about whether I'd say I "like" it or not...

**Comment by vincenthz** [comment]
I can't really answer that either, tricky. btw this could be used for first/second once they are specialized down of  `Arrow` 

```haskell
first :: (FstTy a -> FstTy a) -> a -> a
```

**Comment by ndmitchell** [comment]
Note that `Either` works for `first` but not really `fst` (unless you want `fst` partial). But maybe that doesn't matter and skipping `Either` is fine too.

**Comment by vincenthz** [comment]
it seems to be two differents concept for `first`: one is the `Arrow` one which is compatible with working on any type that has 2 "legs", whereas I guess the other concept works on any polymorphic product type (`first`, `second`, `third`, ...).

Also, just realized my above signature for `first` doesn't make much sense as it does a `a -> a`. not quite as useful as originally thought.

**Comment by ndmitchell** [comment]
Yeah, perhaps ditch `first` entirely - at least the generalisation version.

**Comment by ndmitchell** [comment]
I like what you currently have - but think Thdable and thd might be worth having. Further than that is probably a bad idea. I do that for the extra package.

**Comment by vincenthz** [comment]
I had Thdable and Fthable originally https://github.com/vincenthz/hs-foundation/blob/master/Core/Data/STuple.hs#L42, but yeah up to 3 is probably enough. I like the idea of a generalized version https://github.com/vincenthz/hs-foundation/blob/master/Core/Data/STupleNat.hs for replacing them all eventually though (obviously it's GHC >= 7.10, so not ready for all-version consumption)

**Comment by vincenthz** [comment]
The general todo for this part of foundation is:

[ ] rename module : Core.Data.STuple to Core.Tuple 
[ ] rename module : Core.Data.STupleNat to Core.Tuple.Nat and export properly on a GHC version conditional
[ ] re-add Thrdable
[ ] export properly Fstable/Secondable/Thdable in Core.
[ ] Make sure all necessary tuples got all the required instances
