### ISSUE TITLE
Rename vector to array

### ISSUE THREAD

**Issue by ndmitchell** [vincenthz/hs-foundation#21]
Just a thought, given its the more "natural" name and you are very much replacing base which has array.

**Comment by vincenthz** [comment]
I'm fine with this. I've actually flip flop already from array to vector, but I really don't have a preference about this. renaming the whole thing would take a minute ..

**Comment by ndmitchell** [comment]
I don't have a strong preference, it just feels more natural given existing Haskell conventions and C++ conventions.

**Comment by vincenthz** [comment]
it's now Array everywhere
