### ISSUE TITLE
Add uncons

### ISSUE THREAD

**Issue by ndmitchell** [vincenthz/hs-foundation#24]
I wrote:

```
f_uncons :: F.ByteArray -> Maybe (F.Word8, F.ByteArray)
f_uncons x = case x F.! 0 of
    Nothing -> Nothing
    Just c -> Just (c, F.drop 1 x)
```

But seems like it should be in the library, which is likely more efficient. Naturally generalise to all the things.

**Comment by vincenthz** [comment]
definitely. `unsnoc` comes to mind too

**Comment by vincenthz** [comment]
link to #30 relative to unsnoc

**Comment by vincenthz** [comment]
I've added uncons and unsnoc, but not plumbed through any export yet

**Comment by vincenthz** [comment]
it's all plumbed through, and support for boxed array and String is there too
