### ISSUE TITLE
Add native array slices

### ISSUE THREAD

**Issue by ndmitchell** [vincenthz/hs-foundation#28]
I ported a piece of Hoogle, available at https://gist.github.com/ndmitchell/6828df5eeca3776b32a0420c73dc95ed.

Profiling this code shows 98% of the time is in copyAtRO, even though to convert between ByteString and ByteArray I go via a list... Specifically, 47% of the time is due to break on newlines, and 51% due to uncons on the result. If there were a separating function that could be optimised to avoid the repeated recopy, but that means users can't write their own copy without going _O(n^2)_, which is sad. I think String must support slicing, and given your nice design, that means Array must too.

**Comment by ndmitchell** [comment]
I note that Vector, ByteString and Text all have efficient slicing by default, so it does seem to be the thing to do...

**Comment by vincenthz** [comment]
there's now support for slicing and further extra tests

**Comment by ndmitchell** [comment]
It's now a whole different ballgame of speed - my test gets to where it fails in subsecond rather than over a minute.
