### ISSUE TITLE
Use copyMutableArray# and copyArray#

### ISSUE THREAD

**Issue by ndmitchell** [vincenthz/hs-foundation#29]
Should make things like copyAtRO go much faster. They're native in GHC 7.6 and above, but slightly broken in 7.6, so make it conditional on 7.8 or above.

**Comment by vincenthz** [comment]
yeah it's one of those "written quickly to have something that works but can be optimised". Also once the slice are in place, copying should drop to noise.

**Comment by vincenthz** [comment]
fixed
