### ISSUE TITLE
Detecting operating system, cpu, related information

### ISSUE THREAD

**Issue by vincenthz** [vincenthz/hs-foundation#36]
Add a module and functions to:

* [x] detect operating system
* [x] detect cpu endianness
* [x] detect number cpus

**Comment by NicolasDP** [comment]
👍

**Comment by NicolasDP** [comment]
it'd be nice to have the compiler name and version

**Comment by ndmitchell** [comment]
Is this correct for processor count? See what I do in Shake: https://github.com/ndmitchell/shake/blob/d45223407bba357e9e9498fd840b479581510697/src/General/Extra.hs#L56

Basically in the non threaded RTS number of CPU's == 1.
